version: '3'

services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=0.0.0.0
    depends_on:
      - redis
    networks:
      - poll-tier
  
  redis:
    image: "redis:7-alpine"
    ports:
      - 6379
    networks:
      - poll-tier
      - back-tier
  
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    networks:
      - result-tier
      - back-tier
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./schema.sql:/docker-entrypoint-initdb.d/initdb.sql"
  
  result:
    build: ./result
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - result-tier
      - back-tier

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: